package HYD_bus_details;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextField;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAKSHI
 */
public class Algo extends javax.swing.JFrame {
 public static String pl=null;
public static String dl=null;
 //Out th2= new Out();
 //InitComp sc2 =new InitComp();
    /**
     * Creates new form Algo
     */
    private static Connection cn=null;
private static Statement stmt=null;
private static Statement stmt1=null;
private static Statement stmt2=null;
private static ResultSet rs=null;
private static ResultSet rs1=null;
private static ResultSet rs2=null;
private static ResultSet rsf=null;
private JTextField tfield;
Out th=new Out();
private static final String un="sakshi";
      private static final String passw="sakshi";
       private static final String url="jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=convertToNull";

    public Algo() {
        initComponents();
         this.setLocationRelativeTo(null);
           jLabel2.setBackground(new Color(255,255,255,100));
    }

   public Algo(String p1, String d1) {
        initComponents();
         this.setLocationRelativeTo(null);
           jLabel2.setBackground(new Color(255,255,255,100));
        pl=p1;
        dl=d1;
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        wt2 = new javax.swing.JTextField();
        wt3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        route1 = new javax.swing.JButton();
        route2 = new javax.swing.JButton();
        route3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        wt1 = new javax.swing.JTextField();
        bn3 = new javax.swing.JTextField();
        bn2 = new javax.swing.JTextField();
        bn1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("welcome to GoBus@HYD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setLayout(null);
        jPanel2.add(wt2);
        wt2.setBounds(220, 140, 110, 30);
        jPanel2.add(wt3);
        wt3.setBounds(220, 190, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("BUSES NO.");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(120, 50, 70, 30);

        route1.setText("TOTAL ROUTE");
        route1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                route1ActionPerformed(evt);
            }
        });
        jPanel2.add(route1);
        route1.setBounds(350, 90, 120, 30);

        route2.setText("TOTAL ROUTE");
        route2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                route2ActionPerformed(evt);
            }
        });
        jPanel2.add(route2);
        route2.setBounds(350, 140, 120, 30);

        route3.setText("TOTAL ROUTE");
        route3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                route3ActionPerformed(evt);
            }
        });
        jPanel2.add(route3);
        route3.setBounds(350, 190, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("ARRIVAL TIME");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(230, 50, 90, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(300, 250, 90, 30);
        jPanel2.add(wt1);
        wt1.setBounds(220, 90, 110, 30);
        jPanel2.add(bn3);
        bn3.setBounds(110, 190, 80, 30);
        jPanel2.add(bn2);
        bn2.setBounds(110, 140, 80, 30);
        jPanel2.add(bn1);
        bn1.setBounds(110, 90, 80, 30);

        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 30, 410, 270);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAKSHI\\Desktop\\ITW\\it1.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(-10, -10, 610, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new UserIP().setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void route1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_route1ActionPerformed
        // TODO add your handling code here:
        int flag=0;
        if(bn1.getText()!=null)
        {
             th.setVisible(true);
       this.setVisible(false);
       try {
              cn=DriverManager.getConnection(url,un,passw);
              stmt=cn.createStatement();System.out.println("connect");
              stmt1=cn.createStatement();//System.out.println("connect");
              stmt2=cn.createStatement();//System.out.println("connect");
               
           }
           catch(Exception e){
               e.printStackTrace();
           }
        String p=bn1.getText();
        List<String> ls =new ArrayList<String>();
        String str="";

        
    try {  //Scanner scan = new Scanner(System.in);
       // String text = scan.nextLine();
      //  FileWriter fWriter = null;
      // BufferedWriter writer = null;
               //  fWriter = new FileWriter("text.txt");
       //  FileReader fr= new FileReader("text.txt");
        //  writer = new BufferedWriter(fWriter);
        
        rs2=stmt1.executeQuery("SELECT * from bus_root.search WHERE BUS_NO='"+p+"'");
        while(rs2.next())
        {
          // JTextField tfield = new JTextField(rs2.getString("STATION"));
          //  th.jPanel2.add(tfield);
           // jPanel2.validate();
           // jPanel2.repaint();
          // th.tfield.setText(rs2.getString("STATION"));
            if(rs2.getString("STATION").equals(pl))
            {
                flag=1;
            }
            if(rs2.getString("STATION").equals(dl))
            { str= str+rs2.getString("STATION");
           // ls.add(str);
            str=str + "\n";
                break;
            }
            if(flag==1){
            System.out.println(rs2.getString("STATION"));
            str= str+rs2.getString("STATION");
           // ls.add(str);
            str=str + "\n";
            
           
        try {
         
        //  writer.write(rs2.getString("STATION"));
        //  writer.newLine();
          
          //System.err.println("Your input of " + text.length() + " characters was saved.");
        } catch (Exception e) {
            System.out.println("Error!");
        }}

        }   //     writer.close();
    }catch (SQLException ex) {
        Logger.getLogger(InitComp.class.getName()).log(Level.SEVERE, null, ex);
    }
    FileWriter fWriter = null;
    try {
        fWriter = new FileWriter("text.txt");
        fWriter.write(str);
        fWriter.close();
        
        // tfield.setNa
        
        
        // tfield.setNa
    } catch (IOException ex) {
        Logger.getLogger(InitComp.class.getName()).log(Level.SEVERE, null, ex);
    }
    String fname="D:\\java\\project_1\\text.txt";
    try {
        FileReader fr = new FileReader(fname);
                 try (BufferedReader br = new BufferedReader(fr)) {
                     th.textt.read(br,null);
                 }
        th.textt.requestFocus();
               
    } catch (FileNotFoundException ex) {
        Logger.getLogger(InitComp.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(InitComp.class.getName()).log(Level.SEVERE, null, ex);
    }

        }
    }//GEN-LAST:event_route1ActionPerformed

    private void route2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_route2ActionPerformed
        // TODO add your handling code here:
        int flag=0;
          th.setVisible(true);
       this.setVisible(false);
         try {
              cn=DriverManager.getConnection(url,un,passw);
              stmt=cn.createStatement();System.out.println("connect");
              stmt1=cn.createStatement();//System.out.println("connect");
              stmt2=cn.createStatement();//System.out.println("connect");
               
           }
           catch(Exception e){
               e.printStackTrace();
           }

        String p=bn2.getText();
        List<String> ls =new ArrayList<String>();
        String str="";

        
    try {  //Scanner scan = new Scanner(System.in);
       // String text = scan.nextLine();
      //  FileWriter fWriter = null;
      // BufferedWriter writer = null;
               //  fWriter = new FileWriter("text.txt");
       //  FileReader fr= new FileReader("text.txt");
        //  writer = new BufferedWriter(fWriter);
        
        rs2=stmt1.executeQuery("SELECT * from bus_root.search WHERE BUS_NO='"+p+"'");
        while(rs2.next())
        {
          // JTextField tfield = new JTextField(rs2.getString("STATION"));
          //  th.jPanel2.add(tfield);
           // jPanel2.validate();
           // jPanel2.repaint();
          // th.tfield.setText(rs2.getString("STATION"));
             if(rs2.getString("STATION").equals(pl))
            {
                flag=1;
            }
            if(rs2.getString("STATION").equals(dl))
            { str= str+rs2.getString("STATION");
           // ls.add(str);
            str=str + "\n";
                break;
            }
            if(flag==1){
            System.out.println(rs2.getString("STATION"));
            str= str+rs2.getString("STATION");
           // ls.add(str);
            str=str + "\n";}
            
           
        try {
         
        //  writer.write(rs2.getString("STATION"));
        //  writer.newLine();
          
          //System.err.println("Your input of " + text.length() + " characters was saved.");
        } catch (Exception e) {
            System.out.println("Error!");
        }

        }   //     writer.close();
    }catch (SQLException ex) {
        Logger.getLogger(InitComp.class.getName()).log(Level.SEVERE, null, ex);
    }
    FileWriter fWriter = null;
    try {
        fWriter = new FileWriter("text.txt");
        fWriter.write(str);
        fWriter.close();
        
        // tfield.setNa
        
        
        // tfield.setNa
    } catch (IOException ex) {
        Logger.getLogger(InitComp.class.getName()).log(Level.SEVERE, null, ex);
    }
    String fname="D:\\java\\project_1\\text.txt";
    try {
        FileReader fr = new FileReader(fname);
                 try (BufferedReader br = new BufferedReader(fr)) {
                     th.textt.read(br,null);
                 }
        th.textt.requestFocus();
               
    } catch (FileNotFoundException ex) {
        Logger.getLogger(InitComp.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(InitComp.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_route2ActionPerformed

    private void route3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_route3ActionPerformed
        // TODO add your handling code here:
        int flag=0;
          th.setVisible(true);
       this.setVisible(false);
         try {
              cn=DriverManager.getConnection(url,un,passw);
              stmt=cn.createStatement();System.out.println("connect");
              stmt1=cn.createStatement();//System.out.println("connect");
              stmt2=cn.createStatement();//System.out.println("connect");
               
           }
           catch(Exception e){
               e.printStackTrace();
           }

        String p=bn3.getText();
        List<String> ls =new ArrayList<String>();
        String str="";

        
    try {  //Scanner scan = new Scanner(System.in);
       // String text = scan.nextLine();
      //  FileWriter fWriter = null;
      // BufferedWriter writer = null;
               //  fWriter = new FileWriter("text.txt");
       //  FileReader fr= new FileReader("text.txt");
        //  writer = new BufferedWriter(fWriter);
        
        rs2=stmt1.executeQuery("SELECT * from bus_root.search WHERE BUS_NO='"+p+"'");
        while(rs2.next())
        {
          // JTextField tfield = new JTextField(rs2.getString("STATION"));
          //  th.jPanel2.add(tfield);
           // jPanel2.validate();
           // jPanel2.repaint();
          // th.tfield.setText(rs2.getString("STATION"));
             if(rs2.getString("STATION").equals(pl))
            {
                flag=1;
            }
            if(rs2.getString("STATION").equals(dl))
            { str= str+rs2.getString("STATION");
           // ls.add(str);
            str=str + "\n";
                break;
            }
            if(flag==1){
            System.out.println(rs2.getString("STATION"));
            str= str+rs2.getString("STATION");
           // ls.add(str);
            str=str + "\n";}
            
           
        try {
         
        //  writer.write(rs2.getString("STATION"));
        //  writer.newLine();
          
          //System.err.println("Your input of " + text.length() + " characters was saved.");
        } catch (Exception e) {
            System.out.println("Error!");
        }

        }   //     writer.close();
    }catch (SQLException ex) {
        Logger.getLogger(InitComp.class.getName()).log(Level.SEVERE, null, ex);
    }
    FileWriter fWriter = null;
    try {
        fWriter = new FileWriter("text.txt");
        fWriter.write(str);
        fWriter.close();
        
        // tfield.setNa
        
        
        // tfield.setNa
    } catch (IOException ex) {
        Logger.getLogger(InitComp.class.getName()).log(Level.SEVERE, null, ex);
    }
    String fname="D:\\java\\project_1\\text.txt";
    try {
        FileReader fr = new FileReader(fname);
                 try (BufferedReader br = new BufferedReader(fr)) {
                     th.textt.read(br,null);
                 }
        th.textt.requestFocus();
               
    } catch (FileNotFoundException ex) {
        Logger.getLogger(InitComp.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(InitComp.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_route3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Algo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Algo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Algo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Algo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Algo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField bn1;
    public javax.swing.JTextField bn2;
    public javax.swing.JTextField bn3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JButton route1;
    public javax.swing.JButton route2;
    public javax.swing.JButton route3;
    public javax.swing.JTextField wt1;
    public javax.swing.JTextField wt2;
    public javax.swing.JTextField wt3;
    // End of variables declaration//GEN-END:variables
}
