/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HYD_bus_details;

import java.awt.Color;
import java.util.List;
import static java.awt.SystemColor.text;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
//import D:\java\project_1\src\Project1\text.txt;

/**
 *
 * @author SAKSHI
 */
public class secondtwo extends javax.swing.JFrame {
private static Connection cn=null;
private static Statement stmt=null;
private static Statement stmt1=null;
private static Statement stmt2=null;
private static ResultSet rs=null;
private static ResultSet rs1=null;
private static ResultSet rs2=null;
private static ResultSet rsf=null;
private JTextField tfield;
//private static Statement stmt2=null;
    /*
     * Creates new form login
     */
     private static final String un="sakshi";
      private static final String passw="sakshi";
       private static final String url="jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=convertToNull";

    /**
     * Creates new form second2
     */
    public secondtwo() {
        initComponents();
        this.setLocationRelativeTo(null);
         jLabel2.setBackground(new Color(255,255,255,150));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pl = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("WELCOME TO GoBus@HYD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Enter BUS NUMBER:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 140, 130, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(350, 220, 80, 30);

        pl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select>", "1", "1E", "1K", "1L", "1P", "1V/229", "1/229", "1/92R", "2V", "3CL", "1B", "1V", "1HD", "1MD" }));
        jPanel2.add(pl);
        pl.setBounds(340, 140, 100, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(120, 80, 380, 210);

        jLabel1.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAKSHI\\Desktop\\ITW\\it1.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, -10, 670, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         th.setVisible(true); 
       this.setVisible(false);
         try {
              cn=DriverManager.getConnection(url,un,passw);
              stmt=cn.createStatement();System.out.println("connect");
              stmt1=cn.createStatement();//System.out.println("connect");
              stmt2=cn.createStatement();//System.out.println("connect");
               
           }
           catch(Exception e){
               e.printStackTrace();
           }

        String p=pl.getSelectedItem().toString();
        List<String> ls =new ArrayList<String>();
        String str="";

        
    try {  //Scanner scan = new Scanner(System.in);
       // String text = scan.nextLine();
      //  FileWriter fWriter = null;
      // BufferedWriter writer = null;
               //  fWriter = new FileWriter("text.txt");
       //  FileReader fr= new FileReader("text.txt");
        //  writer = new BufferedWriter(fWriter);
        
        rs2=stmt1.executeQuery("SELECT * from bus_root.search WHERE BUS_NO='"+p+"'");
        while(rs2.next())
        {
          // JTextField tfield = new JTextField(rs2.getString("STATION"));
          //  th.jPanel2.add(tfield);
           // jPanel2.validate();
           // jPanel2.repaint();
          // th.tfield.setText(rs2.getString("STATION"));
            
            System.out.println(rs2.getString("STATION"));
            str= str+rs2.getString("STATION");
           // ls.add(str);
            str=str + "\n";
            
           
        try {
         
        //  writer.write(rs2.getString("STATION"));
        //  writer.newLine();
          
          //System.err.println("Your input of " + text.length() + " characters was saved.");
        } catch (Exception e) {
            System.out.println("Error!");
        }

        }   //     writer.close();
    }catch (SQLException ex) {
        Logger.getLogger(secondtwo.class.getName()).log(Level.SEVERE, null, ex);
    }
    FileWriter fWriter = null;
    try {
        fWriter = new FileWriter("text.txt");
        fWriter.write(str);
        fWriter.close();
        
        // tfield.setNa
        
        
        // tfield.setNa
    } catch (IOException ex) {
        Logger.getLogger(secondtwo.class.getName()).log(Level.SEVERE, null, ex);
    }
    String fname="D:\\java\\project_1\\text.txt";
    try {
        FileReader fr = new FileReader(fname);
        BufferedReader br= new BufferedReader(fr);
        th.textt.read(br,null);
        br.close();
        th.textt.requestFocus();
               
    } catch (FileNotFoundException ex) {
        Logger.getLogger(secondtwo.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(secondtwo.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(secondtwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(secondtwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(secondtwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(secondtwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         try {
              cn=DriverManager.getConnection(url,un,passw);
              stmt=cn.createStatement();System.out.println("connect");
              stmt1=cn.createStatement();//System.out.println("connect");
              stmt2=cn.createStatement();//System.out.println("connect");
               
           }
           catch(Exception e){
               e.printStackTrace();
           }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new secondtwo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JComboBox<String> pl;
    // End of variables declaration//GEN-END:variables
}
